-- Run this once in Supabase SQL Editor.
create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  invite_code text,
  vip_level text default 'VIP1',
  credit_score integer default 100,
  created_at timestamptz default now()
);
create table if not exists public.wallets (
  user_id uuid primary key references auth.users(id) on delete cascade,
  balance numeric(12,2) not null default 0,
  updated_at timestamptz default now()
);
create table if not exists public.products (
  id uuid primary key default gen_random_uuid(), name text not null, price numeric(12,2) not null,
  stock integer not null default 0, image_url text, category text, is_active boolean default true,
  created_at timestamptz default now()
);
create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade,
  product_id uuid references public.products(id), total_amount numeric(12,2) not null,
  status text default 'pending', payment_status text default 'paid', created_at timestamptz default now()
);
create table if not exists public.wallet_transactions (
  id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade,
  amount numeric(12,2) not null, type text not null, status text default 'completed', reference_id uuid, created_at timestamptz default now()
);
create table if not exists public.deposit_requests (
  id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade,
  amount numeric(12,2) not null, payment_method text not null, transaction_id text, status text default 'pending', created_at timestamptz default now()
);
create table if not exists public.withdraw_requests (
  id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade,
  amount numeric(12,2) not null, payment_method text not null, account_number text not null, status text default 'pending', created_at timestamptz default now()
);
create table if not exists public.site_settings (
  id bigint generated by default as identity primary key, site_name text default 'FFT SHOP', announcement text,
  hero_image_url text, updated_at timestamptz default now()
);

create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path=public as $$
begin
  insert into public.profiles(id,invite_code) values(new.id,new.raw_user_meta_data->>'invite_code') on conflict(id) do nothing;
  insert into public.wallets(user_id,balance) values(new.id,0) on conflict(user_id) do nothing;
  return new;
end; $$;
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute function public.handle_new_user();

create or replace function public.place_order(p_product_id uuid) returns jsonb language plpgsql security definer set search_path=public as $$
declare p public.products; w public.wallets; oid uuid;
begin
  select * into p from public.products where id=p_product_id and is_active=true for update;
  if not found then raise exception 'Product not found'; end if;
  if p.stock <= 0 then raise exception 'Product is out of stock'; end if;
  select * into w from public.wallets where user_id=auth.uid() for update;
  if not found then raise exception 'Wallet not found'; end if;
  if w.balance < p.price then raise exception 'Insufficient wallet balance'; end if;
  update public.wallets set balance=balance-p.price,updated_at=now() where user_id=auth.uid();
  update public.products set stock=stock-1 where id=p.id;
  insert into public.orders(user_id,product_id,total_amount,status,payment_status) values(auth.uid(),p.id,p.price,'pending','paid') returning id into oid;
  insert into public.wallet_transactions(user_id,amount,type,status,reference_id) values(auth.uid(),-p.price,'order','completed',oid);
  return jsonb_build_object('order_id',oid,'amount',p.price);
end; $$;
revoke all on function public.place_order(uuid) from public;
grant execute on function public.place_order(uuid) to authenticated;

alter table public.profiles enable row level security;
alter table public.wallets enable row level security;
alter table public.products enable row level security;
alter table public.orders enable row level security;
alter table public.wallet_transactions enable row level security;
alter table public.deposit_requests enable row level security;
alter table public.withdraw_requests enable row level security;
alter table public.site_settings enable row level security;

drop policy if exists "products public read" on public.products;
create policy "products public read" on public.products for select using (is_active=true);
drop policy if exists "settings public read" on public.site_settings;
create policy "settings public read" on public.site_settings for select using (true);

create policy "profile own read" on public.profiles for select using (id=auth.uid());
create policy "wallet own read" on public.wallets for select using (user_id=auth.uid());
create policy "orders own read" on public.orders for select using (user_id=auth.uid());
create policy "tx own read" on public.wallet_transactions for select using (user_id=auth.uid());
create policy "deposit own insert" on public.deposit_requests for insert with check (user_id=auth.uid());
create policy "deposit own read" on public.deposit_requests for select using (user_id=auth.uid());
create policy "withdraw own insert" on public.withdraw_requests for insert with check (user_id=auth.uid());
create policy "withdraw own read" on public.withdraw_requests for select using (user_id=auth.uid());

insert into public.site_settings(site_name,announcement) select 'FFT SHOP','আজকের বিশেষ অফার' where not exists(select 1 from public.site_settings);
insert into public.products(name,price,stock,image_url,category)
select * from (values
 ('Foldable Holder',55.66,104,'https://cdn.yamibuy.net/item/1f7f4dc52c79250df07cd2dc73ac7880_750x750.webp','Accessories'),
 ('Naruto stickers pack',63.26,12,'https://www.google.com/search?tbm=isch&q=Naruto+sticker+pack','Sticker'),
 ('FC Barcelona (Metal Sticker)',72.35,20,'https://www.google.com/search?tbm=isch&q=FC+Barcelona+metal+sticker','Sticker'),
 ('Iraqi Passport (Metal Sticker)',52.35,12,'https://www.google.com/search?tbm=isch&q=Iraqi+passport+metal+sticker','Sticker')
) v(name,price,stock,image_url,category) where not exists(select 1 from public.products);
