const SUPABASE_URL="https://ihxwkebgjvtndynhosbk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY="sb_publishable_wcazcpFqsX1TDEeVROpoDQ_rDGXDBDR";
const db=window.supabase.createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
function normalizePhone(v){v=v.trim().replace(/[\s-]/g,"");if(/^01\d{9}$/.test(v))return "+880"+v.slice(1);return v}
function togglePassword(id,el){const x=document.getElementById(id);x.type=x.type==="password"?"text":"password";el.textContent=x.type==="password"?"●":"○"}
function showError(msg){document.getElementById("error").textContent=msg||""}
(async()=>{const {data}=await db.auth.getSession();if(data.session)location.href="index.html"})()
const lf=document.getElementById("loginForm");
if(lf)lf.addEventListener("submit",async e=>{e.preventDefault();showError("");const phone=normalizePhone(document.getElementById("phone").value),password=document.getElementById("password").value;if(!/^\+\d{8,15}$/.test(phone)){showError("সঠিক মোবাইল নম্বর দিন");return}if(password.length<6){showError("পাসওয়ার্ড কমপক্ষে ৬ অক্ষরের হতে হবে");return}const {error}=await db.auth.signInWithPassword({phone,password});if(error){showError(error.message.includes("Invalid login")?"মোবাইল নম্বর বা পাসওয়ার্ড সঠিক নয়":error.message);return}location.href="index.html"});
const rf=document.getElementById("registerForm");
if(rf)rf.addEventListener("submit",async e=>{e.preventDefault();showError("");const phone=normalizePhone(document.getElementById("phone").value),password=document.getElementById("password").value,confirm=document.getElementById("confirm").value,invite=document.getElementById("invite").value.trim();if(!/^\+\d{8,15}$/.test(phone)){showError("সঠিক মোবাইল নম্বর দিন");return}if(password.length<6){showError("পাসওয়ার্ড কমপক্ষে ৬ অক্ষরের হতে হবে");return}if(password!==confirm){showError("দুইটি পাসওয়ার্ড একই নয়");return}const {data,error}=await db.auth.signUp({phone,password,options:{data:{invite_code:invite||null}}});if(error){showError(error.message);return}if(data.session)location.href="index.html";else{showError("রেজিস্ট্রেশন হয়েছে। Supabase Phone Auth verification সম্পন্ন করে লগইন করুন।");setTimeout(()=>location.href="login.html",2200)}});
